# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldb', '0002_auto_20160315_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='smiles',
            field=models.CharField(default='test', max_length=500),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='summary_formula',
            field=models.CharField(default='Te1S2T11', max_length=99),
        ),
    ]
