# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moldb', '0003_auto_20160315_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='inchi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='molecule',
            name='inchikey',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='molecule',
            name='mol_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='name',
            field=models.CharField(blank=True, max_length=99),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='pic',
            field=models.ImageField(blank=True, upload_to='/pics'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='smiles',
            field=models.CharField(default='test', max_length=300),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='summary_formula',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
